import { Plant, Store, Post, TrendingTopic } from './types';

export const PLANTS: Plant[] = [
  {
    id: '1',
    name: 'Monstera Deliciosa',
    scientificName: 'Monstera deliciosa',
    category: 'Indoor',
    difficulty: 2,
    sunlight: 'Medium',
    water: 'Medium',
    soil: 'Well-draining peat-based',
    description: 'The iconic Swiss Cheese Plant, known for its large, heart-shaped leaves with natural holes.',
    price: 45,
    image: 'https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&q=80&w=800',
    health: 95,
    lastWatered: '2 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '2',
    name: 'Spider Plant',
    scientificName: 'Chlorophytum comosum',
    category: 'Indoor',
    difficulty: 1,
    sunlight: 'Medium',
    water: 'Medium',
    soil: 'Well-draining potting mix',
    description: 'Known for its air-purifying qualities and ease of care. Produces "babies" that can be easily propagated.',
    price: 22,
    image: 'https://images.unsplash.com/photo-1545241047-6083a3684587?auto=format&fit=crop&q=80&w=800',
    secondaryImage: 'https://images.unsplash.com/photo-1599598425947-5202ed56419a?auto=format&fit=crop&q=80&w=800',
    health: 100,
    lastWatered: '3 days ago',
    isPetFriendly: true,
    isAirPurifying: true,
    isLowLight: true
  },
  {
    id: '3',
    name: 'Fiddle Leaf Fig',
    scientificName: 'Ficus lyrata',
    category: 'Indoor',
    difficulty: 4,
    sunlight: 'High',
    water: 'Medium',
    soil: 'Rich, well-draining',
    description: 'A popular statement plant with large, violin-shaped leaves. Requires consistent care.',
    price: 65,
    image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&q=80&w=800',
    health: 80,
    lastWatered: '3 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '4',
    name: 'Blue Agave',
    scientificName: 'Agave tequilana',
    category: 'Rare',
    difficulty: 3,
    sunlight: 'High',
    water: 'Low',
    soil: 'Sandy, rocky soil',
    description: 'A striking succulent with blue-green leaves. The source of tequila.',
    price: 120,
    image: 'https://images.unsplash.com/photo-1525498128493-380d1990a112?auto=format&fit=crop&q=80&w=800',
    health: 90,
    lastWatered: '2 weeks ago',
    isPetFriendly: false,
    isAirPurifying: false,
    isLowLight: false
  },
  {
    id: '5',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    category: 'Medicinal',
    difficulty: 2,
    sunlight: 'High',
    water: 'Low',
    soil: 'Well-draining succulent mix',
    description: 'Known for its healing gel, this succulent is both beautiful and practical.',
    price: 15,
    image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&q=80&w=800',
    health: 98,
    lastWatered: '5 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '6',
    name: 'Japanese Maple',
    scientificName: 'Acer palmatum',
    category: 'Outdoor',
    difficulty: 3,
    sunlight: 'Medium',
    water: 'High',
    soil: 'Moist, acidic, well-drained',
    description: 'A stunning ornamental tree with delicate, colorful foliage.',
    price: 150,
    image: 'https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&q=80&w=800',
    health: 85,
    lastWatered: 'Yesterday',
    isPetFriendly: true,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '7',
    name: 'Bird of Paradise',
    scientificName: 'Strelitzia reginae',
    category: 'Indoor',
    difficulty: 3,
    sunlight: 'High',
    water: 'Medium',
    soil: 'Rich, loamy',
    description: 'A dramatic plant with large, banana-like leaves and spectacular orange flowers.',
    price: 85,
    image: 'https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&q=80&w=800',
    health: 92,
    lastWatered: '4 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '8',
    name: 'Boston Fern',
    scientificName: 'Nephrolepis exaltata',
    category: 'Indoor',
    difficulty: 4,
    sunlight: 'Medium',
    water: 'High',
    soil: 'Peat-based, moist',
    description: 'A lush, feathery fern that loves humidity and adds a classic touch to any room.',
    price: 30,
    image: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&q=80&w=800',
    health: 75,
    lastWatered: 'Today',
    isPetFriendly: true,
    isAirPurifying: true,
    isLowLight: true
  },
  {
    id: '9',
    name: 'Lavender',
    scientificName: 'Lavandula angustifolia',
    category: 'Medicinal',
    difficulty: 2,
    sunlight: 'High',
    water: 'Low',
    soil: 'Well-draining, alkaline',
    description: 'Prized for its fragrant flowers and calming properties. Great for sunny spots.',
    price: 20,
    image: 'https://images.unsplash.com/photo-1463320898484-cdee8141c787?auto=format&fit=crop&q=80&w=800',
    health: 96,
    lastWatered: '3 days ago',
    isPetFriendly: true,
    isAirPurifying: false,
    isLowLight: false
  },
  {
    id: '10',
    name: 'Peace Lily',
    scientificName: 'Spathiphyllum',
    category: 'Indoor',
    difficulty: 2,
    sunlight: 'Low',
    water: 'Medium',
    soil: 'All-purpose potting mix',
    description: 'Elegant white blooms and dark green leaves. Excellent at cleaning indoor air.',
    price: 35,
    image: 'https://plus.unsplash.com/premium_photo-1676068243733-df1880c2aef8?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8cGVhY2UlMjBsaWx5fGVufDB8fDB8fHww',
    health: 88,
    lastWatered: '2 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: true
  },
  {
    id: '11',
    name: 'Pothos',
    scientificName: 'Epipremnum aureum',
    category: 'Indoor',
    difficulty: 1,
    sunlight: 'Low',
    water: 'Medium',
    soil: 'Standard potting mix',
    description: 'The ultimate beginner plant. Fast-growing vines with heart-shaped leaves.',
    price: 18,
    image: 'https://images.unsplash.com/photo-1596724878582-76f1a8fdc24f?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cG90aG9zfGVufDB8fDB8fHww',
    health: 99,
    lastWatered: '5 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: true
  },
  {
    id: '12',
    name: 'ZZ Plant',
    scientificName: 'Zamioculcas zamiifolia',
    category: 'Indoor',
    difficulty: 1,
    sunlight: 'Low',
    water: 'Low',
    soil: 'Well-draining mix',
    description: 'Thrives on neglect. Shiny, waxy leaves that look great in any corner.',
    price: 28,
    image: 'https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&q=80&w=800',
    health: 100,
    lastWatered: '2 weeks ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: true
  },
  {
    id: '13',
    name: 'Rubber Tree',
    scientificName: 'Ficus elastica',
    category: 'Indoor',
    difficulty: 2,
    sunlight: 'Medium',
    water: 'Medium',
    soil: 'Well-draining',
    description: 'Bold, dark leaves that add a dramatic touch to your interior.',
    price: 40,
    image: 'https://images.unsplash.com/photo-1679321750278-1606c0d1ec9e?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8cnViYmVyJTIwdHJlZXxlbnwwfHwwfHx8MA%3D%3D',
    health: 94,
    lastWatered: '4 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '14',
    name: 'Calathea Orbifolia',
    scientificName: 'Calathea orbifolia',
    category: 'Rare',
    difficulty: 5,
    sunlight: 'Medium',
    water: 'High',
    soil: 'Peat-rich, moist',
    description: 'Stunning round leaves with silver stripes. A true showstopper for experts.',
    price: 55,
    image: 'https://media.istockphoto.com/id/1369385915/photo/calathea-orbifolia-plant-in-yellow-wicker-basket.webp?a=1&b=1&s=612x612&w=0&k=20&c=Y9aUrLywzBTFrYleD20WTQr1gZsmdX69cR241lzcw_E=',
    health: 70,
    lastWatered: 'Today',
    isPetFriendly: true,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '15',
    name: 'Jade Plant',
    scientificName: 'Crassula ovata',
    category: 'Indoor',
    difficulty: 2,
    sunlight: 'High',
    water: 'Low',
    soil: 'Succulent mix',
    description: 'A symbol of good luck. Thick, woody stems and fleshy green leaves.',
    price: 24,
    image: 'https://images.unsplash.com/photo-1611843467160-25afb8df1074?auto=format&fit=crop&q=80&w=800',
    health: 96,
    lastWatered: '10 days ago',
    isPetFriendly: false,
    isAirPurifying: false,
    isLowLight: false
  },
  {
    id: '16',
    name: 'Prayer Plant',
    scientificName: 'Maranta leuconeura',
    category: 'Indoor',
    difficulty: 3,
    sunlight: 'Medium',
    water: 'High',
    soil: 'Moist, well-draining',
    description: 'Leaves fold up at night like hands in prayer. Beautiful patterns.',
    price: 32,
    image: 'https://images.unsplash.com/photo-1639756534497-d3271888337c?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8cHJheWVyJTIwcGxhbnR8ZW58MHx8MHx8fDA%3D',
    health: 85,
    lastWatered: 'Yesterday',
    isPetFriendly: true,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '17',
    name: 'Swiss Cheese Vine',
    scientificName: 'Monstera adansonii',
    category: 'Rare',
    difficulty: 3,
    sunlight: 'Medium',
    water: 'Medium',
    soil: 'Peat-based',
    description: 'A smaller, trailing relative of the Deliciosa with more delicate fenestrations.',
    price: 38,
    image: 'https://images.unsplash.com/photo-1596660562354-0dbc5d1d0fb4?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3dpc3MlMjBjaGVlc2UlMjB2aW5lJTIwcGxhbnR8ZW58MHx8MHx8fDA%3D',
    health: 91,
    lastWatered: '3 days ago',
    isPetFriendly: false,
    isAirPurifying: true,
    isLowLight: false
  },
  {
    id: '18',
    name: 'String of Pearls',
    scientificName: 'Senecio rowleyanus',
    category: 'Rare',
    difficulty: 4,
    sunlight: 'High',
    water: 'Low',
    soil: 'Cactus mix',
    description: 'Unique trailing succulent with pea-shaped leaves. Needs bright light.',
    price: 42,
    image: 'https://media.istockphoto.com/id/857756386/photo/hanging-million-heart-plant-in-garden.webp?a=1&b=1&s=612x612&w=0&k=20&c=miopBGo9G2zlEQ3PRxUNpowlTzxBf0A5RoZLgQKDli8=',
    health: 78,
    lastWatered: '1 week ago',
    isPetFriendly: false,
    isAirPurifying: false,
    isLowLight: false
  }
];

export const STORES: Store[] = [
  {
    id: '1',
    name: 'Green Haven Nursery',
    distance: '1.2 km',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    address: '123 Garden Lane, Bloom City',
    lat: 40.7128,
    lng: -74.0060
  },
  {
    id: '2',
    name: 'The Plant Collective',
    distance: '3.5 km',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&q=80&w=800',
    address: '456 Flora St, Green District',
    lat: 40.7306,
    lng: -73.9352
  },
  {
    id: '3',
    name: 'Urban Jungle',
    distance: '5.8 km',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&q=80&w=800',
    address: '789 Concrete Jungle Ave',
    lat: 40.7589,
    lng: -73.9851
  },
  {
    id: '4',
    name: 'Botanical Bliss',
    distance: '2.1 km',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&q=80&w=800',
    address: '101 Petal Path, Bloom City',
    lat: 40.7200,
    lng: -74.0100
  },
  {
    id: '5',
    name: 'Rare Roots',
    distance: '4.2 km',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    address: '202 Exotic Way, Green District',
    lat: 40.7400,
    lng: -73.9500
  },
  {
    id: '6',
    name: 'The Succulent Spot',
    distance: '6.5 km',
    rating: 4.4,
    image: 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?auto=format&fit=crop&q=80&w=800',
    address: '303 Desert Drive, Sand Valley',
    lat: 40.7600,
    lng: -73.9900
  },
  {
    id: '7',
    name: 'Leafy Living',
    distance: '0.8 km',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1592150621744-aca64f48394a?auto=format&fit=crop&q=80&w=800',
    address: '404 Verdant View, Bloom City',
    lat: 40.7100,
    lng: -74.0000
  },
  {
    id: '8',
    name: 'Bloom & Branch',
    distance: '3.1 km',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&q=80&w=800',
    address: '505 Floral Blvd, Green District',
    lat: 40.7350,
    lng: -73.9400
  },
  {
    id: '9',
    name: 'Nature\'s Nook',
    distance: '5.2 km',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&q=80&w=800',
    address: '606 Wildwood Way, Sand Valley',
    lat: 40.7550,
    lng: -73.9800
  }
];

export const POSTS: Post[] = [
  {
    id: '1',
    user: {
      name: 'LeafLover99',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Felix'
    },
    image: 'https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&q=80&w=800',
    caption: 'My Monstera just put out a new leaf! Look at those fenestrations! 🌿✨ #monstera #plantgrowth #urbanjungle',
    likes: 124,
    comments: [
      { id: 'c1', user: 'PlantMom', text: 'So beautiful! What fertilizer do you use?', time: '1h ago' },
      { id: 'c2', user: 'GreenThumb', text: 'Amazing progress!', time: '30m ago' }
    ],
    shares: 45,
    time: '2h ago',
    tags: ['monstera', 'plantgrowth', 'urbanjungle']
  },
  {
    id: '2',
    user: {
      name: 'PlantParent_Sarah',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah'
    },
    image: 'https://images.unsplash.com/photo-1463320898484-cdee8141c787?auto=format&fit=crop&q=80&w=800',
    video: 'https://assets.mixkit.co/videos/preview/mixkit-forest-stream-in-the-sunlight-529-large.mp4',
    caption: 'Morning sun hitting the collection just right. ☀️🌱 #morningvibes #plantshelfie',
    likes: 89,
    comments: [
      { id: 'c3', user: 'SunSeeker', text: 'That light is perfect!', time: '2h ago' }
    ],
    shares: 12,
    time: '5h ago',
    tags: ['morningvibes', 'plantshelfie']
  },
  {
    id: '3',
    user: {
      name: 'EcoWarrior',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Eco'
    },
    image: 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&q=80&w=800',
    caption: 'Just added this rare beauty to my collection! 🌵💎 #rareplants #cactuslove',
    likes: 256,
    comments: [],
    shares: 88,
    time: '1d ago',
    tags: ['rareplants', 'cactuslove']
  }
];

export const TRENDING_TOPICS: TrendingTopic[] = [
  { id: '1', name: '#MonsteraMonday', postsCount: '12.5k' },
  { id: '2', name: '#UrbanJungle', postsCount: '45.2k' },
  { id: '3', name: '#RarePlantAlert', postsCount: '8.9k' },
  { id: '4', name: '#PlantCareTips', postsCount: '22.1k' },
  { id: '5', name: '#Sustainability', postsCount: '15.4k' }
];
